version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules 

  server:
    build: ./server
    ports:
      - "3002:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - ./server/.env
